version: 2.1

parameters:
  test_1:
    type: boolean
    default: false
  test_2:
    type: boolean
    default: false
  test_3:
    type: boolean
    default: false

jobs:
  test:
    docker:
      - image: circleci/python:3
    steps:
      - run:
          name: This should run after everything else
          command: echo "I was runnning"

workflows:
  version: 2.1
  default:
    jobs:
      - test:
          filters:
            branches:
              only: .*
            tags:
              only: .*
          name: default
  test_1_workflow:
    when: << pipeline.parameters.test_1 >>
    jobs:
      - test:
          filters:
            branches:
              only: .*
            tags:
              only: .*
          name: test_1
  test_2_workflow:
    when: << pipeline.parameters.test_2 >>
    jobs:
      - test:
          filters:
            branches:
              only: .*
            tags:
              only: .*
          name: test_2
  test_3_workflow:
    when: << pipeline.parameters.test_3 >>
    jobs:
      - test:
          filters:
            branches:
              only: .*
            tags:
              only: .*
          name: test_3
